### ISSUE TITLE
Question - Should the terminal be scrolling?

### ISSUE THREAD

**Issue by hayesmaker** [madbence/node-drawille#17]
should the terminal constantly be scrolling while animations are running?

<img width="1550" alt="screen shot 2018-02-11 at 09 57 23" src="https://user-images.githubusercontent.com/593429/36072112-fe00039e-0f11-11e8-8b2f-c7eb7932c1af.png">

**Comment by madbence** [comment]
`drawille` is just a thin library, it's supposed to be used together with eg. [`blessed`](https://www.npmjs.com/package/blessed) or with some other terminal interface api.

if you're annoyed by the scrolling, you don't want to use complicated libraries, and you don't care about supporting windows, you can just `console.log('\x1b[1;1H' + frame)`, which will move the cursor to the top left corner. see [xterm control sequences](http://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Functions-using-CSI-_-ordered-by-the-final-character_s_) for more details.
